### ISSUE TITLE
[CheckBox]TODO

### ISSUE THREAD

**Issue by DevinYin17** [DevinYin17/Resources#4]
- [x] complete the checkbox directive without checkbox label
- [ ] three kind of style(follow this: http://elemefe.github.io/mint-ui/#/switch)
- [ ] compare with the os-checkbox
